menu:
    Blog: /
    Archive: /archives/
    About: /about/
    Zhihu: https://www.zhihu.com/people/zheduanyin/activities
    GitHub: https://github.com/filosfino
    Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/favicon.png

# Comment
# e.g disqus: seansun
disqus: filosfino
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x
ga: UA-94010149-1

# Copyright Infomation
startyear: 2016
